### ISSUE TITLE
(conda-forge py38 support) The following specifications were found to be incompatible with each other:

### ISSUE THREAD

**Issue by eamGit** [facebook/prophet#1227]
Hi, i am trying to install fbprophet through annaconda by using: conda install -c conda-forge fbprophet.   However i  keep getting incompatible specification errors : I am fairly new to this , i have also tried  conda update --all bu this made no difference

Any help and guidance to fix this problem is appreciated?

The following specifications were found to be incompatible with each other:
Package setuptools conflicts for:
fbprophet -> setuptools
python=3.7 -> pip -> setuptools
Package msgpack-python conflicts for:
fbprophet -> python=3.6 -> pip -> cachecontrol -> msgpack-python
Package certifi conflicts for:
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
fbprophet -> python=3.6 -> pip -> requests -> certifi[version='>=2017.4.17']
Package pip conflicts for:
fbprophet -> python=3.6 -> pip
python=3.7 -> pip
Package ca-certificates conflicts for:
python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
fbprophet -> python=3.6 -> ca-certificates
Package libpython conflicts for:
fbprophet -> matplotlib -> libpython
Package wincertstore conflicts for:
python=3.7 -> pip -> setuptools -> wincertstore[version='>=0.2']
fbprophet -> setuptools -> wincertstore[version='>=0.2']
Package wheel conflicts for:
python=3.7 -> pip -> wheel
fbprophet -> python=3.6 -> pip -> wheel

**Comment by trevor-pope** [comment]
What is the version of your Python? I have a feeling the requirements.txt file isn't updated for Python 3.8

**Comment by eamGit** [comment]
Python version 3.7.5

**Comment by trevor-pope** [comment]
Can you give us the results of running `conda info` while you have your environment activated?

**Comment by eamGit** [comment]
active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\emaroun\.condarc
 populated config files : C:\Users\emaroun\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.11
         python version : 3.7.5.final.0
       virtual packages :
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-32
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-32
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\emaroun\.conda\pkgs
                          C:\Users\emaroun\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\emaroun\.conda\envs
                          C:\Users\emaroun\AppData\Local\conda\conda\envs
               platform : win-32
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.5
Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False

**Comment by bletham** [comment]
The issue here is that the fbprophet-feedstock hasn't been updated for Py3.8. The automated attempt to do this failed (https://github.com/conda-forge/fbprophet-feedstock/pull/22) and now I'm first fixing a new issue related to the holidays package (https://github.com/conda-forge/fbprophet-feedstock/pull/25) and then will re-try the build for Py3.8.

**Comment by osguru** [comment]
fbprophet is not compatible with python 3.8. 

Requirement pystan has package for python 3.8 and successfully installed for anaconda.

Kindly create fbprophet package for python 3.8.

Thanks

Here is output:
---------------
(py38) PS C:\Users\pat> conda install -c conda-forge fbprophet
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.-
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - fbprophet -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that..

**Comment by bletham** [comment]
I had thought this would happen automatically with the v0.6 push when I closed it, but then found out in https://github.com/conda-forge/fbprophet-feedstock/pull/30 that it hadn't. I got a bit stuck on that (some really bizarre build issues) and lost track of this issue. I just asked the conda forge bot to re-try the build for py38 so hopefully that works, but if you have any experience with conda forge please do help out over on that PR.

**Comment by scholarazwa** [comment]
Hi, any update on this?
I'm still unable to install FB Prophet while on Python 3.8.
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - fbprophet -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

**Comment by bletham** [comment]
This should be fixed now by https://github.com/conda-forge/fbprophet-feedstock/pull/33, which got fbprophet to build in py38. If anyone is still running into issues with this please reopen!

**Comment by sudeshna-py** [comment]
Hey, am getting an attribute error in this code, and I'm unable to fix this.

![a](https://user-images.githubusercontent.com/71181547/93707448-575cb080-fb4c-11ea-8ca0-5bb17e332c4a.png)

**Comment by Siya-Tuks** [comment]
Hi

Please assist, I am still getting the error when trying to get fbprophet using !conda install -c conda-forge fbprophet -y

the error reads:

Building graph of deps:   0%|          | 0/4 [00:00<?, ?it/s]
Examining python=3.8:   0%|          | 0/4 [00:00<?, ?it/s]  
Examining fbprophet:  25%|##5       | 1/4 [00:00<00:00,  4.76it/s]
Examining fbprophet:  50%|#####     | 2/4 [00:00<00:00,  9.53it/s]
Examining @/win-32::__archspec==1=x86:  50%|#####     | 2/4 [00:01<00:00,  9.53it/s]
Examining @/win-32::__archspec==1=x86:  75%|#######5  | 3/4 [00:01<00:00,  2.32it/s]
Examining @/win-32::__win==0=0:  75%|#######5  | 3/4 [00:01<00:00,  2.32it/s]       
                                                                             

Determining conflicts:   0%|          | 0/4 [00:00<?, ?it/s]
Examining conflict for python fbprophet:   0%|          | 0/4 [00:00<?, ?it/s]
                                                                              

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - fbprophet -> python[version='2.7.*|3.5.*|3.6.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by bletham** [comment]
@Siya-Tuks I'm not sure what might be happening because conda forge does have a py38 windows build for fbprophet. You can see it in the list of files here: https://anaconda.org/conda-forge/fbprophet/files  win-64/fbprophet-0.7.1-py38h7ae7562_0.tar.bz2

I don't think I have any ideas on how to debug, other than that I'm in the middle of pushing a new version (1.0) to conda forge and so whenever they review that and it goes in, hopefully that will work.
