### ISSUE TITLE
cannot import name 'easter'

### ISSUE THREAD

**Issue by nescobar** [facebook/prophet#1292]
I have a job running daily forecasts with Prophet. Starting today, there is this error when trying to import a 'easter' package. This happens when importing get_holiday_names and make_holidays_df from fbprophet.make_holidays package.

Any ideas on how to resolve this?

Thanks.

**Comment by sarikayamerts** [comment]
holidays package is updated, structure is completely different. I'll be on it.

**Comment by sarikayamerts** [comment]
or you can stick to the previous version of holidays, as pip install holidays==0.9.12

**Comment by nescobar** [comment]
> or you can stick to the previous version of holidays, as pip install holidays==0.9.12

I'm applying _pip install holidays==0.9.12_ before importing Prophet but getting the same error

**Comment by flaboss** [comment]
holidays==0.9 worked fine for me using prophet ==0.4

**Comment by nescobar** [comment]
There is no version 0.9 according to the release history
https://pypi.org/project/holidays/#history

**Comment by nescobar** [comment]
Not sure why, but it works now with _pip install holidays==0.9.12_

**Comment by dr-prodigy** [comment]
Here
https://github.com/dr-prodigy/python-holidays/issues/277
you'll find a fix for this issue, which is depending on a wrong reference made to easter, which is not part of holidays.

**Comment by vkarpov15** [comment]
I fixed this problem by uninstalling prophet :+1:

**Comment by brandy888** [comment]
Still getting the easter issue - I have tried uninstalling both prophet and holidays
