### ISSUE TITLE
error when running pip install fbprophet

### ISSUE THREAD

**Issue by dark-spark2** [facebook/prophet#1775]
Hi,
I tried to run pip install fbprophet on docker:

`FROM public.ecr.aws/lambda/python:3.8
RUN pip --no-cache-dir install \
      ephem \
      pystan \
      fbprophet 
`

But got the following error:
`    ERROR: Command errored out with exit status 1:
     command: /var/lang/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l79apfcp/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l79apfcp/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9yrgxbdz/install-record.txt --single-version-externally-managed --compile --install-headers /var/lang/include/python3.8/fbprophet
         cwd: /tmp/pip-install-l79apfcp/fbprophet/
    Complete output (10 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    Importing plotly failed. Interactive plots will not work.
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_dfdaf2b8ece8a02eb11f050ec701c0ec NOW.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /var/lang/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l79apfcp/fbprophet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l79apfcp/fbprophet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9yrgxbdz/install-record.txt --single-version-externally-managed --compile --install-headers /var/lang/include/python3.8/fbprophet Check the logs for full command output.
WARNING: You are using pip version 20.2.1; however, version 20.3.3 is available.
You should consider upgrading via the '/var/lang/bin/python3.8 -m pip install --upgrade pip' command.`

please recommend on workaround,
Thanks!

**Comment by bletham** [comment]
The `command 'gcc' failed with exit status 1` usually means the C++ toolchain isn't working, but can you check the logs for the full command output to see what else might be there?

You can also check if pystan is working after it is installed:
```Python
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
y.mean()  # should be close to 0
```

And make sure the necessary C++ packages are installed, and that you have enough RAM in your VM.

#1306, #1175, and #1102 may be useful (especially the last).

**Comment by arid-mangoss** [comment]
The cpp compiler issues can be pretty hard to fix. Make sure you follow this https://facebook.github.io/prophet/docs/installation.html#python. 

Also, I've noticed that R is quick and easy to install on Windows compared to the python version. You may try that if you can't get an install to work via PIP

**Comment by octavd** [comment]
Hey,

I had this problem also but i've managed to make it work with the following workaround.

Before installing fbprophet you have to install pystan.

However if you will install like this -> pip install pystan it will fail at building fbprophet because it will grab version 2.19.*.* that is not compatible with GCC version.

Solution:

1) pip install pystan==2.18.0.0

2) pip install fbprophet

**Comment by icankeep** [comment]
> Hey,
> 
> I had this problem also but i've managed to make it work with the following workaround.
> 
> Before installing fbprophet you have to install pystan.
> 
> However if you will install like this -> pip install pystan it will fail at building fbprophet because it will grab version 2.19._._ that is not compatible with GCC version.
> 
> Solution:
> 
> 1. pip install pystan==2.18.0.0
> 2. pip install fbprophet

In this way, the problem is solved, thanks

**Comment by igloro** [comment]
> > Hey,
> > I had this problem also but i've managed to make it work with the following workaround.
> > Before installing fbprophet you have to install pystan.
> > However if you will install like this -> pip install pystan it will fail at building fbprophet because it will grab version 2.19._._ that is not compatible with GCC version.
> > Solution:
> > 
> > 1. pip install pystan==2.18.0.0
> > 2. pip install fbprophet
> 
> In this way, the problem is solved, thanks

ERROR: No matching distribution found for pystan==2.18.0.0

**Comment by epignatelli** [comment]
11 months later `pip install fbprophet` is still broken on Apple Silicon, python 3.9 and python 3.7.

**Comment by cmapz2** [comment]
Fellas I fixed it (regular old windows 10 laptop with Python 3.6). At least it worked for me :)

`pip install pystan==2.17.1`
`pip install fbprophet`

**Comment by turkalpmd** [comment]
Just run !pip install prophet

**Comment by RafaRivera75** [comment]
> Hey,
> 
> I had this problem also but i've managed to make it work with the following workaround.
> 
> Before installing fbprophet you have to install pystan.
> 
> However if you will install like this -> pip install pystan it will fail at building fbprophet because it will grab version 2.19._._ that is not compatible with GCC version.
> 
> Solution:
> 
> 1. pip install pystan==2.18.0.0
> 2. pip install fbprophet

Gracias por el aporte funcionó perfecto.

**Comment by Bharathisudha** [comment]
import pandas as pd
import plotly.express as px
from fbprophet import Prophet    #approach 1


the output I got is.....

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-48-3e1b8d449d7d>](https://localhost:8080/#) in <module>
      1 import pandas as pd
      2 import plotly.express as px
----> 3 from fbprophet import Prophet    #approach 1


ModuleNotFoundError: No module named 'fbprophet'
______________________________________________________________________________________________________________

import pandas as pd
import plotly.express as px
#!pip install prophet             #approach 2
#import prophet


the output I got is.....{Got Successful here, but the error is at creating the model using fit()}

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: prophet in /usr/local/lib/python3.8/dist-packages (1.1.2)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.8/dist-packages (from prophet) (4.64.1)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.8/dist-packages (from prophet) (2.8.2)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.8/dist-packages (from prophet) (1.22.4)
Requirement already satisfied: pandas>=1.0.4 in /usr/local/lib/python3.8/dist-packages (from prophet) (1.3.5)
Requirement already satisfied: convertdate>=2.1.2 in /usr/local/lib/python3.8/dist-packages (from prophet) (2.4.0)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from prophet) (3.5.3)
Requirement already satisfied: cmdstanpy>=1.0.4 in /usr/local/lib/python3.8/dist-packages (from prophet) (1.1.0)
Requirement already satisfied: LunarCalendar>=0.0.9 in /usr/local/lib/python3.8/dist-packages (from prophet) (0.0.9)
Requirement already satisfied: holidays>=0.14.2 in /usr/local/lib/python3.8/dist-packages (from prophet) (0.20)
Requirement already satisfied: pymeeus<=1,>=0.3.13 in /usr/local/lib/python3.8/dist-packages (from convertdate>=2.1.2->prophet) (0.5.12)
Requirement already satisfied: korean-lunar-calendar in /usr/local/lib/python3.8/dist-packages (from holidays>=0.14.2->prophet) (0.3.1)
Requirement already satisfied: hijri-converter in /usr/local/lib/python3.8/dist-packages (from holidays>=0.14.2->prophet) (2.2.4)
Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from LunarCalendar>=0.0.9->prophet) (2022.7.1)
Requirement already satisfied: ephem>=3.7.5.3 in /usr/local/lib/python3.8/dist-packages (from LunarCalendar>=0.0.9->prophet) (4.1.4)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (4.38.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (23.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (8.4.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (1.4.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.0->prophet) (1.15.0)

________________________________________________________________________________________________________________________

The solution given above by others is not working for me, it's just taking too many minutes & that's it. Not installing at all!

Any solutions, please..!

**Comment by knownbymanoj** [comment]
> import pandas as pd import plotly.express as px from fbprophet import Prophet #approach 1
> 
> the output I got is.....
> 
> ModuleNotFoundError Traceback (most recent call last) in 1 import pandas as pd 2 import plotly.express as px ----> 3 from fbprophet import Prophet #approach 1
> 
> ModuleNotFoundError: No module named 'fbprophet'
> 
> import pandas as pd import plotly.express as px #!pip install prophet #approach 2 #import prophet
> 
> the output I got is.....{Got Successful here, but the error is at creating the model using fit()}
> 
> Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/ Requirement already satisfied: prophet in /usr/local/lib/python3.8/dist-packages (1.1.2) Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.8/dist-packages (from prophet) (4.64.1) Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.8/dist-packages (from prophet) (2.8.2) Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.8/dist-packages (from prophet) (1.22.4) Requirement already satisfied: pandas>=1.0.4 in /usr/local/lib/python3.8/dist-packages (from prophet) (1.3.5) Requirement already satisfied: convertdate>=2.1.2 in /usr/local/lib/python3.8/dist-packages (from prophet) (2.4.0) Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from prophet) (3.5.3) Requirement already satisfied: cmdstanpy>=1.0.4 in /usr/local/lib/python3.8/dist-packages (from prophet) (1.1.0) Requirement already satisfied: LunarCalendar>=0.0.9 in /usr/local/lib/python3.8/dist-packages (from prophet) (0.0.9) Requirement already satisfied: holidays>=0.14.2 in /usr/local/lib/python3.8/dist-packages (from prophet) (0.20) Requirement already satisfied: pymeeus<=1,>=0.3.13 in /usr/local/lib/python3.8/dist-packages (from convertdate>=2.1.2->prophet) (0.5.12) Requirement already satisfied: korean-lunar-calendar in /usr/local/lib/python3.8/dist-packages (from holidays>=0.14.2->prophet) (0.3.1) Requirement already satisfied: hijri-converter in /usr/local/lib/python3.8/dist-packages (from holidays>=0.14.2->prophet) (2.2.4) Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from LunarCalendar>=0.0.9->prophet) (2022.7.1) Requirement already satisfied: ephem>=3.7.5.3 in /usr/local/lib/python3.8/dist-packages (from LunarCalendar>=0.0.9->prophet) (4.1.4) Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (4.38.0) Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (23.0) Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (3.0.9) Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (0.11.0) Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (8.4.0) Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.0.0->prophet) (1.4.4) Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.0->prophet) (1.15.0)
> 
> The solution given above by others is not working for me, it's just taking too many minutes & that's it. Not installing at all!
> 
> Any solutions, please..!

This tutorial helped me. check this out 

https://medium.com/data-folks-indonesia/installing-fbprophet-prophet-for-time-series-forecasting-in-jupyter-notebook-7de6db09f93e

**Comment by knownbymanoj** [comment]
This tutorial helped me. check this out

https://medium.com/data-folks-indonesia/installing-fbprophet-prophet-for-time-series-forecasting-in-jupyter-notebook-7de6db09f93e

**Comment by Selithrarion** [comment]
> Fellas I fixed it (regular old windows 10 laptop with Python 3.6). At least it worked for me :)
> 
> `pip install pystan==2.17.1` `pip install fbprophet`

yea, fixed!
